In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:/Users/Hp/Desktop/vs_part/drug data_csv.csv')

In [3]:
df

,Cell_Line_Name,Drug_Name,Cosmic_ID,Drug_ID,TCGA_Classification,PSA,Tissue,Tissue_Sub-type,IS_Mutated,IC50
0,697,Zoledronate,906800,1802,UNCLASSIFIED,2.0,blood,lymphoblastic_leukemia,0,2.324538
1,697,ZM447439,906800,1050,UNCLASSIFIED,10.0,blood,lymphoblastic_leukemia,0,-0.758715
2,697,YK-4-279,906800,1239,UNCLASSIFIED,20.0,blood,lymphoblastic_leukemia,0,-0.571283
3,697,XAV939,906800,1268,UNCLASSIFIED,10.0,blood,lymphoblastic_leukemia,0,4.316320
4,697,WZ4003,906800,1614,UNCLASSIFIED,10.0,blood,lymphoblastic_leukemia,0,2.138157
...,...,...,...,...,...,...,...,...,...,...
243461,ZR-75-30,615590,909907,1839,BRCA,3.0,breast,breast,0,4.222822
243462,ZR-75-30,150412,909907,1836,BRCA,3.0,breast,breast,0,4.274296
243463,ZR-75-30,123829,909907,1820,BRCA,3.0,breast,breast,0,4.683226
243464,ZR-75-30,123138,909907,1824,BRCA,1.0,breast,breast,0,4.137158
243465,ZR-75-30,50869,909907,1826,BRCA,3.0,breast,breast,0,4.743439

In [4]:
columns_to_remove = ['Cell_Line_Name', 'Drug_Name']
df= df.drop(columns_to_remove, axis=1)

In [5]:
df

,Cosmic_ID,Drug_ID,TCGA_Classification,PSA,Tissue,Tissue_Sub-type,IS_Mutated,IC50
0,906800,1802,UNCLASSIFIED,2.0,blood,lymphoblastic_leukemia,0,2.324538
1,906800,1050,UNCLASSIFIED,10.0,blood,lymphoblastic_leukemia,0,-0.758715
2,906800,1239,UNCLASSIFIED,20.0,blood,lymphoblastic_leukemia,0,-0.571283
3,906800,1268,UNCLASSIFIED,10.0,blood,lymphoblastic_leukemia,0,4.316320
4,906800,1614,UNCLASSIFIED,10.0,blood,lymphoblastic_leukemia,0,2.138157
...,...,...,...,...,...,...,...,...
243461,909907,1839,BRCA,3.0,breast,breast,0,4.222822
243462,909907,1836,BRCA,3.0,breast,breast,0,4.274296
243463,909907,1820,BRCA,3.0,breast,breast,0,4.683226
243464,909907,1824,BRCA,1.0,breast,breast,0,4.137158
243465,909907,1826,BRCA,3.0,breast,breast,0,4.743439

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder

In [7]:
import xgboost as xgb
import catboost 
from catboost import CatBoostRegressor, Pool

In [8]:
nan_values=df.isna().sum()
nan_values

Cosmic_ID                 0
Drug_ID                   0
TCGA_Classification    1067
PSA                       0
Tissue                  359
Tissue_Sub-type         359
IS_Mutated                0
IC50                      0
dtype: int64

In [9]:
df= df.dropna()

In [10]:
nan_values=df.isna().sum()
nan_values

Cosmic_ID              0
Drug_ID                0
TCGA_Classification    0
PSA                    0
Tissue                 0
Tissue_Sub-type        0
IS_Mutated             0
IC50                   0
dtype: int64

In [11]:
df['TCGA_Classification'] = df['TCGA_Classification'].astype(str)

df['Tissue'] = df['Tissue'].astype(str)
df['Tissue_Sub-type'] = df['Tissue_Sub-type'].astype(str)

C:\Users\Hp\AppData\Local\Temp\ipykernel_15460\741288072.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TCGA_Classification'] = df['TCGA_Classification'].astype(str)
C:\Users\Hp\AppData\Local\Temp\ipykernel_15460\741288072.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Tissue'] = df['Tissue'].astype(str)
C:\Users\Hp\AppData\Local\Temp\ipykernel_15460\741288072.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Tissue_Sub-type'] = df['Tissue_Sub-type'].astype(str)

In [12]:
X = df.drop('IC50', axis=1)  # Replace "target_variable" with the name of your target variable column
y = df["IC50"]

In [13]:
X

,Cosmic_ID,Drug_ID,TCGA_Classification,PSA,Tissue,Tissue_Sub-type,IS_Mutated
0,906800,1802,UNCLASSIFIED,2.0,blood,lymphoblastic_leukemia,0
1,906800,1050,UNCLASSIFIED,10.0,blood,lymphoblastic_leukemia,0
2,906800,1239,UNCLASSIFIED,20.0,blood,lymphoblastic_leukemia,0
3,906800,1268,UNCLASSIFIED,10.0,blood,lymphoblastic_leukemia,0
4,906800,1614,UNCLASSIFIED,10.0,blood,lymphoblastic_leukemia,0
...,...,...,...,...,...,...,...
243461,909907,1839,BRCA,3.0,breast,breast,0
243462,909907,1836,BRCA,3.0,breast,breast,0
243463,909907,1820,BRCA,3.0,breast,breast,0
243464,909907,1824,BRCA,1.0,breast,breast,0
243465,909907,1826,BRCA,3.0,breast,breast,0

In [14]:
y

0         2.324538
1        -0.758715
2        -0.571283
3         4.316320
4         2.138157
            ...
243461    4.222822
243462    4.274296
243463    4.683226
243464    4.137158
243465    4.743439
Name: IC50, Length: 242399, dtype: float64

In [15]:
print(df.dtypes)

Cosmic_ID                int64
Drug_ID                  int64
TCGA_Classification     object
PSA                    float64
Tissue                  object
Tissue_Sub-type         object
IS_Mutated               int64
IC50                   float64
dtype: object

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [17]:
pool_train=Pool(X_train,y_train,cat_features=['TCGA_Classification','Tissue','Tissue_Sub-type'])
pool_test=Pool(X_test,cat_features=['TCGA_Classification','Tissue','Tissue_Sub-type'])

In [18]:
import time
import numpy as np

In [19]:
start=time.time()
cbr=CatBoostRegressor(iterations=100)

In [20]:
cbr.fit(pool_train)
y_pred=cbr.predict(X_test)

from sklearn.metrics import r2_score as RSquared

cb_rsquared=np.sqrt(RSquared(y_test,y_pred))

print("R Squared for CatBoost: ", np.mean(cb_rsquared))

end=time.time()
diff=end-start
print('Excecution Time: ',diff)

Learning rate set to 0.5
0:	learn: 2.3440779	total: 288ms	remaining: 28.6s
1:	learn: 2.1705460	total: 437ms	remaining: 21.4s
2:	learn: 2.1042376	total: 571ms	remaining: 18.5s
3:	learn: 2.0721889	total: 704ms	remaining: 16.9s
4:	learn: 2.0200763	total: 865ms	remaining: 16.4s
5:	learn: 1.9931802	total: 989ms	remaining: 15.5s
6:	learn: 1.9454632	total: 1.11s	remaining: 14.8s
7:	learn: 1.9235309	total: 1.23s	remaining: 14.1s
8:	learn: 1.8981001	total: 1.37s	remaining: 13.8s
9:	learn: 1.8864879	total: 1.49s	remaining: 13.4s
10:	learn: 1.8704425	total: 1.6s	remaining: 12.9s
11:	learn: 1.8655460	total: 1.73s	remaining: 12.7s
12:	learn: 1.8623426	total: 1.86s	remaining: 12.4s
13:	learn: 1.8258646	total: 2.05s	remaining: 12.6s
14:	learn: 1.7921951	total: 2.19s	remaining: 12.4s
15:	learn: 1.7763725	total: 2.3s	remaining: 12.1s
16:	learn: 1.7645937	total: 2.4s	remaining: 11.7s
17:	learn: 1.7438838	total: 2.51s	remaining: 11.5s
18:	learn: 1.7315489	total: 2.63s	remaining: 11.2s
19:	learn: 1.7222568	total: 2.75s	remaining: 11s
20:	learn: 1.7115243	total: 2.86s	remaining: 10.8s
21:	learn: 1.6932845	total: 2.98s	remaining: 10.6s
22:	learn: 1.6884832	total: 3.09s	remaining: 10.3s
23:	learn: 1.6757473	total: 3.21s	remaining: 10.2s
24:	learn: 1.6645602	total: 3.32s	remaining: 9.96s
25:	learn: 1.6583691	total: 3.44s	remaining: 9.78s
26:	learn: 1.6125507	total: 3.54s	remaining: 9.58s
27:	learn: 1.6059059	total: 3.67s	remaining: 9.43s
28:	learn: 1.5987776	total: 3.78s	remaining: 9.26s
29:	learn: 1.5881332	total: 4.02s	remaining: 9.38s
30:	learn: 1.5860581	total: 4.28s	remaining: 9.52s
31:	learn: 1.5845613	total: 4.4s	remaining: 9.34s
32:	learn: 1.5713348	total: 4.5s	remaining: 9.15s
33:	learn: 1.5633869	total: 4.62s	remaining: 8.96s
34:	learn: 1.5572090	total: 4.73s	remaining: 8.78s
35:	learn: 1.5412604	total: 4.84s	remaining: 8.61s
36:	learn: 1.5388026	total: 4.96s	remaining: 8.45s
37:	learn: 1.5317972	total: 5.07s	remaining: 8.28s
38:	learn: 1.5261680	total: 5.18s	remaining: 8.1s
39:	learn: 1.5250408	total: 5.28s	remaining: 7.92s
40:	learn: 1.5227224	total: 5.39s	remaining: 7.75s
41:	learn: 1.5153178	total: 5.49s	remaining: 7.58s
42:	learn: 1.5103083	total: 5.6s	remaining: 7.42s
43:	learn: 1.4987241	total: 5.71s	remaining: 7.27s
44:	learn: 1.4965829	total: 5.82s	remaining: 7.12s
45:	learn: 1.4908568	total: 5.94s	remaining: 6.97s
46:	learn: 1.4860183	total: 6.04s	remaining: 6.81s
47:	learn: 1.4777700	total: 6.15s	remaining: 6.67s
48:	learn: 1.4700329	total: 6.26s	remaining: 6.52s
49:	learn: 1.4674055	total: 6.37s	remaining: 6.37s
50:	learn: 1.4665430	total: 6.5s	remaining: 6.25s
51:	learn: 1.4608425	total: 6.62s	remaining: 6.11s
52:	learn: 1.4581979	total: 6.72s	remaining: 5.96s
53:	learn: 1.4543558	total: 6.83s	remaining: 5.82s
54:	learn: 1.4471936	total: 6.96s	remaining: 5.7s
55:	learn: 1.4446382	total: 7.08s	remaining: 5.56s
56:	learn: 1.4434450	total: 7.23s	remaining: 5.45s
57:	learn: 1.4392052	total: 7.37s	remaining: 5.34s
58:	learn: 1.4373116	total: 7.51s	remaining: 5.22s
59:	learn: 1.4360999	total: 7.64s	remaining: 5.1s
60:	learn: 1.4353498	total: 7.76s	remaining: 4.96s
61:	learn: 1.4344325	total: 7.86s	remaining: 4.82s
62:	learn: 1.4324829	total: 7.97s	remaining: 4.68s
63:	learn: 1.4294477	total: 8.11s	remaining: 4.56s
64:	learn: 1.4271329	total: 8.25s	remaining: 4.44s
65:	learn: 1.4250898	total: 8.4s	remaining: 4.33s
66:	learn: 1.4210388	total: 8.53s	remaining: 4.2s
67:	learn: 1.4196982	total: 8.65s	remaining: 4.07s
68:	learn: 1.4172991	total: 8.75s	remaining: 3.93s
69:	learn: 1.4155911	total: 8.86s	remaining: 3.79s
70:	learn: 1.4134294	total: 8.96s	remaining: 3.66s
71:	learn: 1.4111977	total: 9.06s	remaining: 3.52s
72:	learn: 1.4094299	total: 9.17s	remaining: 3.39s
73:	learn: 1.4077874	total: 9.28s	remaining: 3.26s
74:	learn: 1.4049274	total: 9.38s	remaining: 3.13s
75:	learn: 1.4009918	total: 9.49s	remaining: 3s
76:	learn: 1.3988390	total: 9.6s	remaining: 2.87s
77:	learn: 1.3980132	total: 9.7s	remaining: 2.74s
78:	learn: 1.3971620	total: 9.81s	remaining: 2.61s
79:	learn: 1.3951742	total: 9.91s	remaining: 2.48s
80:	learn: 1.3939390	total: 10s	remaining: 2.35s
81:	learn: 1.3927342	total: 10.1s	remaining: 2.23s
82:	learn: 1.3900324	total: 10.3s	remaining: 2.11s
83:	learn: 1.3843049	total: 10.4s	remaining: 1.99s
84:	learn: 1.3803045	total: 10.6s	remaining: 1.86s
85:	learn: 1.3768789	total: 10.7s	remaining: 1.74s
86:	learn: 1.3768607	total: 10.8s	remaining: 1.62s
87:	learn: 1.3768552	total: 10.9s	remaining: 1.49s
88:	learn: 1.3747053	total: 11s	remaining: 1.36s
89:	learn: 1.3718958	total: 11.2s	remaining: 1.24s
90:	learn: 1.3704842	total: 11.3s	remaining: 1.12s
91:	learn: 1.3700290	total: 11.4s	remaining: 991ms
92:	learn: 1.3693118	total: 11.5s	remaining: 866ms
93:	learn: 1.3680080	total: 11.6s	remaining: 741ms
94:	learn: 1.3665362	total: 11.7s	remaining: 617ms
95:	learn: 1.3657024	total: 11.8s	remaining: 493ms
96:	learn: 1.3643624	total: 11.9s	remaining: 369ms
97:	learn: 1.3624721	total: 12s	remaining: 246ms
98:	learn: 1.3607950	total: 12.1s	remaining: 123ms
99:	learn: 1.3591630	total: 12.3s	remaining: 0us
R Squared for CatBoost:  0.8692126223150375
Excecution Time:  13.157954454421997

In [21]:
from sklearn.metrics import mean_squared_error

y_pred = cbr.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

MSE: 1.8880967602048253

In [22]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)

MAE: 1.047867349477269

In [23]:
rmse = mean_squared_error(y_test, y_pred, squared=False)
print("RMSE:", rmse)

RMSE: 1.3740803325151063